= Base Specification

_Related to CEF eDelivery AS4 link:{base}Features[2.1]._

NOTE: *From CEF:* +
The table is not very clear in what is different.
For example, it is not straightforward for the user to understand that the difference in Message Correlation is the fact that the reftomessageid is dropped from the eDelivery requirements.

NOTE: *From OpenPEPPOL:* +
Added paragraph above table and included original values from CEF for comparisson. Chapter 2 is intended as an high level overview like <<CEFeDeliveryAS4>> 2.1, details related to changed functionality may be found in chapter 3.

The bellow table contains a high level overview of changed features in OpenPEPPOL AS4 specification compared to table of features in <<CEFeDeliveryAS4>>.

[cols="1,2,2", options="header"]
.Changed functionality for OpenPEPPOL
|===
| Functionality
| OpenPEPPOL AS4
| <<CEFeDeliveryAS4>>

| Exchange Patterns
| One Way
| One Way or Two Way (*)

| Exchange Pattern Bindings
| Push
| Push, Pull and Sync (*)

| Message Correlation
| ebMS 3.0 "ConversationId"
| ebMS 3.0 "RefToMessageId" and "ConversationId"
|===


== Notation

The key words MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT, SHOULD, SHOULD NOT, RECOMMENDED, MAY, and OPTIONAL in this specification are to be interpreted as described in <<RFC2119>>.
