= OpenPEPPOL AS4 Profile
OpenPEPPOL AISBL
v0.9.0
:doctype: book
:icons: font
:toc: left
:toclevels: 2
:source-highlighter: coderay
:source-language: xml
:sectanchors:
:sectnums:


== Description

This document describes aspects special to OpenPEPPOL when implementing the link:#ref_CEF[[CEF\]] eDelivery AS4 specification for use in the PEPPOL network.

In short is use of AS4 in the PEPPOL network for transmission of asyncronius messages between corner 2 and corner 3 in a Four Corner Topology using PEPPOL PKI for authentication and SMP/SML for discovery.

//This document describes the PEPPOL AS4 profile by mirroring the link:#ref_CEF[[CEF\]] specification. Description of how the PEPPOL Network operates (exchange between C1-C2/C3-C4, lookup using Busdox SML/Busdox SMP, SBDH specification) is left out by intention.


== Base Specification

_Related to CEF eDelivery AS4 2.1._

[cols="1,2", options="header"]
.Changed functionality for OpenPEPPOL
|===
| Functionality
| ebMS 3.0 AS4

| Exchange Patterns
| One Way

| Exchange Pattern Bindings
| Push

| Message Correlation
| ebMS 3.0 "ConversationId"
|===


=== Notation

The key words MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT, SHOULD, SHOULD NOT, RECOMMENDED, MAY, and OPTIONAL in this specification are to be interpreted as described in [RFC2119].


== Implementation in OpenPEPPOL


=== Exchange Patterns

_Related to CEF eDelivery AS4 3.2.1._

==== One-Way/Push

==== One-Way/Pull

One-Way/Pull is not required by CEF, and OpenPEPPOL MUST NOT use One-Way/Pull.

==== Two-Way/Push-and-Push

==== Two-Way/Sync

Due to asynconius transmission in OpenPEPPOL is Two-Way/Sync not used.




=== Message Correlation

_Related to CEF eDelivery AS4 3.2.2 and 3.4.2._

*eb:RefToMessageId* is out of scope for OpenPEPPOL.


=== Configuration of Transport Level Security (TLS)

_Related to CEF eDelivery AS4 3.2.6 and 3.4.5._

Access points part of the PEPPOL network does not exchange information related to IPs and ports upfront of transmitting messages.

Receiving access points MUST configure TLS on port *443*. Sending access points need only to allow outbound transmissions using port *443*.

TLS MUST use a valid certificate issued by a trusted issuing agency. Issuing agency MUST be trusted by Oracle (Java), Mozilla and Windows (.NET).


=== Agreement

_Related to CEF eDelivery AS4 3.2.2._

Value of *eb:AgreementRef* is a fixed value in OpenPEPPOL.


=== Error Handling

_Related to CEF eDelivery AS4 3.2.5._

[cols="1,2", options="header"]
.P-Modes for OpenPEPPOL
|===
| P-Mode
| Value

| PMode[].ErrorHandling.Report.ProcessErrorNotifyProducer
| Fixed value: `true`
|===


==== Feedback when receiver is not serviced

When receiving a business document the Access Point will need to check whether it services the addressed participant to be able to deliver the message. When a MSH allows to execute custom validations of the content of a User Message during the ebMS message processing, it is RECOMMENDED that the Access Point includes the check on the addressee and generates and sends back an ebMS Error in case the addressed participant is not serviced by the Access Point.

The _errorCode_ attribute of the generated _Error_ MUST be set to `EBMS:0004` (Other error) and its severity attribute MUST be set to _failure_. Furthermore the _errorDetail_ attribute MUST have value `PEPPOL:NOT_SERVICED` to indicate that the addressed participant is not serviced by the Access Point.


=== Party Identification

_Related to CEF eDelivery AS4 3.4.1 and 4.1.2._

[cols="1,2", options="header"]
.P-Modes for OpenPEPPOL
|===
| P-Mode
| Value

| PMode.[Initiator \| Responder].Party
| One PartyId with value the Subject CNAME of the PEPPOL Access Point Certificate issued to the Access Point, e.g. APP_1000000100 +
Fixed value for PartyId.type: `urn:fdc:peppol.eu:2017:identifiers:ap`

| PMode.[Initiator \| Responder].Role
| Fixed value: `urn:fdc:peppol.eu:2017:roles:ap:as4`
|===

Use of *trackingIdentifier* is not specified by OpenPEPPOL and may not be used.


=== Service, Action and Role

_Related to CEF eDelivery AS4 3.4.4._

When sending the business document the Access Point MUST set *PMode[1].BusinessInfo.Service to* the PEPPOL process identifier as specified in the PEPPOL BIS. The *PMode[1].BusinessInfo.Service.type* MUST be set to the fixed value `urn:fdc:peppol.eu:2017:identifiers:proc-id`. The Service value MUST be formatted as follows (similar to the generic URL formatting defined in [BUSDOX-CDF]): «scheme identifier»::«process identifier value». The values for scheme and process identifier SHALL NOT use URL percent encoding. *PMode[1].BusinessInfo.Action* MUST be set to business document’s encoded document type identifier as 284 defined in the PEPPOL BIS. The document type identifiers MUST be formatted as specified in link:ref_PEPPOL-ID-POL[[PEPPOL-ID-POL\]].

[cols="1,2", options="header"]
.P-Modes for OpenPEPPOL
|===
| P-Mode
| Value

| PMode[1].BusinessInfo.Service
| The PEPPOL Process identifier of the business document formatted as follows: «scheme id»::«process id value» +
Example: `cenbii-procid-ubl::urn:www.cenbii.eu:profile:bii01:ver2.0`

| PMode[1].BusinessInfo.Service.type
| Fixed value: `urn:fdc:peppol.eu:2017:identifiers:proc-id`

| PMode[1].BusinessInfo.Action
| The encoded PEPPOL Document type identifier of the business document, as registered in the SMP: //DocumentIdentifier +
Example: `busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0::2.1`
|===


=== Use of PEPPOL PKI

_Related to CEF eDelivery AS4 3.2.6 and 3.4.5._

[cols="1,2", options="header"]
.P-Modes for OpenPEPPOL
|===
| P-Mode
| Value

| PMode[].Security.X509.Signature.Certificate
| PEPPOL certificate of sending AP.

| PMode[].Security.X509.Encryption.Certificate
| PEPPOL certificate of receiving AP fetched from SMP.
|===


=== Use of default MPC

[cols="1,2", options="header"]
.Changed P-modes for OpenPEPPOL
|===
| Processing Mode Parameter
| Value in the eDelivery Common Profile

| PMode[].BusinessInfo.MPC
| Fixed value: `http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC`
|===


=== Use of SBDH

_Related to CEF eDelivery AS4 4.2._

Use of SBDH is MANDATORY in OpenPEPPOL.

Use of standalone SBDH is not suppored in OpenPEPPOL.

Use of *sh:Manifest* is not supported in OpenPEPPOL.


=== Message packaging

_Related to CEF eDelivery AS4 3.4.6._

As defined in section 5 of [ebMS3CORE] the payloads of an ebMS User Message may be contained in either the SOAP Body or separate MIME attachments. Since this profile however uses the AS4 Compression Feature (see below) which applies only to payloads packaged in attachments the Access Point MUST include all payloads as MIME attachments.

NOTE: When sending large messages an Access Point MAY use the http chunked transfer encoding to enable more streamlined processing. As specified in section 4.1 of [RFC7230] Access Points MUST support this encoding when receiving messages.

The "Content-Disposition" MIME header as described in section 5.1.9 of [AS4-Profile] SHALL NOT be used to exchange the filename of an attached payload. If the exchanged business document consists of multiple parts that need to be identifiable to enable cross referencing between parts a _Part Property_ with name _PartId_ MUST be used (see also issue 52 registered with the OASIS ebMS TC). The actual identifier must be provided by the application that composes the multi-part business document.

NOTE: This does not imply that an Access Point cannot include this header in the MIME message, but only that it should not be used to identify the payload and a receiving Access Point MAY ignore the header.


=== Test Service

_Related to CEF eDelivery AS4 3.2.4 and 3.4.3._



== P-Mode Parameters

_Related to CEF eDelivery AS4 3.5._

[cols="1,2", options="header"]
.Changed P-modes for OpenPEPPOL
|===
| Processing Mode Parameter
| Value in the eDelivery Common Profile

| PMode.Agreement
| Fixed value: `urn:fdc:peppol.eu:2017:agreements:tia:ap_provider`

| PMode.MEP
| Fixed value: `http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/oneWay`

| PMode.MEPBinding
| Fixed value: `http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/push`

| PMode.Initiator.Party
| Please see link:#_3_4_1[3.4.1]

| PMode.Initiator.Party.type
| Fixed value: `urn:fdc:peppol.eu:2017:identifiers:ap`

| PMode.Initiator.Role
| Fixed value: `urn:fdc:peppol.eu:2017:roles:ap:as4`

| PMode.Responder.Party
| Please see link:#_3_4_1[3.4.1]

| PMode.Responder.Party.type
| Fixed value: `urn:fdc:peppol.eu:2017:identifiers:ap`

| PMode.Responder.Role
| Fixed value: `urn:fdc:peppol.eu:2017:roles:ap:as4`

| PMode[].BusinessInfo.Service
| Please see link:#_3_4_4[3.4.4]

| PMode[].BusinessInfo.Service.type
| Fixed value: `urn:fdc:peppol.eu:2017:identifiers:proc-id`

| PMode[].BusinessInfo.Action
| Please see link:#_3_4_4[3.4.4]

| PMode[].BusinessInfo.MPC
| Fixed value: `http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC`

| PMode[].ErrorHandling.Report.ProcessErrorNotifyProducer
| Fixed value: `true`
|===


== Non-AS4 related aspects


=== Capability Lookup

_Related to CEF eDelivery AS4 4.3 and 4.4._

Lookup functionalities in the PEPPOL network uses Busdox SMP and Busdox SML according to [PEPPOL-SML] and [PEPPOL-SMP].

OpenPEPPOL will upgrade to OASIS BDXL and OASIS BDXR SMP as part of a later mirgraton project.


===	SMP transport profile identifier

_Related to CEF eDelivery AS4 4.4._

Receiving Access Points MUST ensure that they have configured one or more P-Modes so they can receive messages for all combinations of document type and process (including scheme) identifiers referenced by AS4 endpoints (i.e. _transportProfile_ attribute has value `peppol-transport-as4-v1_0`) that they have registered in the SMP. Note that an Access Point MAY use a "generic" P-Mode to receive the registered business documents. Such a generic P-Mode only defines the parameters related to the Access Point itself but no business document specific ones.

== Conformance


== References

[[ref_CEF]]
* [CEF] eDelivery AS4 - 1.13, 2018-05-30. https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eDelivery+AS4+-+1.13

[[ref_ebMS3CORE]]
* [ebMS3CORE] OASIS ebXML Messaging Services Version 3.0: Part 1, Core Features, 1 October 2007, OASIS Standard, http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/core/ebms_core-3.0-spec.pdf

[[ref_PEPPOL-ID-POL]]
* [PEPPOL-ID-POL] PEPPOL Transport Infrastructure Policy for use of Identifiers, Version 3.0, 3 February 2014, https://openpeppol.github.io/documentation/TransportInfrastructure/old/PEPPOL_Policy%20for%20use%20of%20identifiers-300.pdf
