= Service, Action and Role

_Related to CEF eDelivery AS4 link:{base}Service,ActionandRole[3.4.4]._

When sending the business document the Access Point MUST set *PMode[1].BusinessInfo.Service* to the Peppol process identifier as specified for the business document. The *PMode[1].BusinessInfo.Service.type* MUST be set to the Peppol process identifier schema as specified for the business document (`cenbii-procid-ubl` as default when not specified). The values for scheme and process identifier SHALL NOT use URL percent encoding.

*PMode[1].BusinessInfo.Action* MUST be set to business document’s encoded document type identifier as defined for the business document (`busdox-docid-qns` as default when document type identifier scheme is not specified). The document type identifiers MUST be formatted as specified in <<PEPPOL-ID-POL>>.

// TODO

[%autowidth.stretch, options="header"]
.P-Modes for OpenPeppol
|===
| P-Mode Parameter | Value

| PMode[1].BusinessInfo.Service
| The Peppol Process Identifier Value of the business document.

Example: +
`urn:www.cenbii.eu:profile:bii01:ver2.0`

| PMode[1].BusinessInfo.Service.type
| The Peppol Process Identifier Scheme of the business document.

Example: +
`cenbii-procid-ubl`

| PMode[1].BusinessInfo.Action
| The Peppol Document Type Identifier of the business document formatted as follows: +
`«scheme id»::«document type id value»`

Example: +
`busdox-docid-qns::urn:oasis:names:specification:ubl:schema:
xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:
biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:
peppol5a:ver2.0::2.1`
|===
