= Error Handling

_Related to CEF eDelivery AS4 link:{base}ErrorHandling[3.2.5]._

[cols="1,2", options="header"]
.P-Modes for OpenPEPPOL
|===
| P-Mode
| Value

| PMode[].ErrorHandling.Report.ProcessErrorNotifyProducer
| Fixed value: `true`
|===

== Feedback when receiver is not serviced

When receiving a business document the Access Point will need to check whether it services the addressed participant to be able to deliver the message. When a MSH allows to execute custom validations of the content of a User Message during the ebMS message processing, it is RECOMMENDED that the Access Point includes the check on the addressee and generates and sends back an ebMS Error in case the addressed participant is not serviced by the Access Point.

The `errorCode` attribute of the generated `Error` MUST be set to `EBMS:0004` (Other error) and its severity attribute MUST be set to `failure`. Furthermore the `errorDetail` attribute MUST have value `PEPPOL:NOT_SERVICED` to indicate that the addressed participant is not serviced by the Access Point.
