= Message packaging

_Related to CEF eDelivery AS4 link:{base}MessagePayloadandFlowProfile[3.4.6]._

As defined in section 5 of <<ebMS3CORE>> the payloads of an ebMS User Message may be contained in either the SOAP Body or separate MIME attachments. Since this profile however uses the AS4 Compression Feature (see below) which applies only to payloads packaged in attachments the Access Point MUST include all payloads as MIME attachments.

NOTE: When sending large messages an Access Point MAY use the http chunked transfer encoding to enable more streamlined processing. As specified in section 4.1 of <<RFC7230>> Access Points MUST support this encoding when receiving messages.

The "Content-Disposition" MIME header as described in section link:http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/profiles/AS4-profile/v1.0/os/AS4-profile-v1.0-os.html#__RefHeading__26456_1909778835[5.1.9] of <<AS4-Profile>> SHALL NOT be used to exchange the filename of an attached payload. AS4 implementations not supporting removal of the MIME header MUST use `payload.xml` as filename.
