= Party Identification

_Related to CEF eDelivery AS4 link:{base}PartyIdentification[3.4.1] and link:{base}AddressingandPartyIdentification[4.1.2]._

[cols="1,2", options="header"]
.P-Modes for OpenPEPPOL
|===
| P-Mode
| Value

| PMode.[Initiator \| Responder].Party
| One PartyId with value the Subject CNAME of the PEPPOL Access Point Certificate issued to the Access Point, e.g. APP_1000000100 +
Fixed value for PartyId.type: `urn:fdc:peppol.eu:2017:identifiers:ap`

| PMode.[Initiator \| Responder].Role
| Fixed value: `urn:fdc:peppol.eu:2017:roles:ap:as4`
|===

NOTE: *From CEF:* +
Other domains separate two separate values for the initiator for the responder, even if they have fixed values, rather than one fixed value for all cases. Some products (at least in the past) had problems if the same value is used for role in From and To.

Use of *trackingIdentifier* is not specified by OpenPEPPOL and MUST NOT be used.

NOTE: *From CEF:* +
Why is there a reference to trackingIdentifier in a section on party identification?  The trackingIdentifier is an identifier to (end-to-end) track messages, not parties.
