= Configuration of Transport Level Security (TLS)

_Related to CEF eDelivery AS4 link:{base}Security[3.2.6] and link:{base}Security.1[3.4.5]._

Access Points that are part of the PEPPOL network do not exchange information related to IPs and ports upfront of transmitting messages as descibed in <<CEFeDeliveryAS4>>.

In the PEPPOL network the access point MUST be configured according to the following:

* Receiving access points MUST configure TLS on port *443*.
* Sending access points need only to allow outbound transmissions using port *443*.

TLS MUST use a valid certificate issued by a trusted issuing agency.
The issuing agency MUST be trusted by Oracle (Java) and Microsoft (.NET).

NOTE: *From CEF*: +
Lists of trusted TLS CAs are not programming language specific but set by operating systems/distributions on servers (e.g. Windows, Ubuntu) or on networking equipment (e.g. Cisco IOS). Other AS4 profiles have formulated the constraint as requirements on CAs, e.g. adherence to EN 319 412-4 or the CA Browser Forum baseline requirements, in order to not have to mention specific (commercial) products.

NOTE: *From OpenPEPPOL*: +
Stays for now. Should be included in PEPPOL TIA in the long run. CEF could include the content of their comment in the CEF eDelivery AS4 specification.
